- name: Get Secrets
  hosts: localhost
  tasks:
    - name: Create Common Secrets SSH file
      ansible.builtin.lineinfile:
        path: secrets.json
        line: "{{lookup('community.hashi_vault.hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.priya9sdr.online:8200 validate_certs=False')}}"
        create: yes

    - name: Create App Secrets file
      ansible.builtin.lineinfile:
        path: app.json
        line: "{{lookup('community.hashi_vault.hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{vault_token}} url=https://vault.priya9sdr.online:8200 validate_certs=False')}}"
        create: yes