- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Adding Application User
  ansible.builtin.user:
    name: expense

- name: Copy Expense Nginx Configuration
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import App Pre Requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req


- name: start nginx
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: yes

- name: import newrelic nginx setup
  ansible.builtin.import_role:
    name: newrelic
    tasks_from: nginx

  # restarted
  #comment




