
  - name: clean the old content
    ansible.builtin.file:
      path: "{{ app_loc }}"
      state: absent

  - name: create App directory
    ansible.builtin.file:
      path: "{{ app_loc }}"
      state: directory
      owner: "{{app_user}}"
      group: "{{app_user}}"


  - name: Download and extract App content
    ansible.builtin.unarchive:
      src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
      dest: "{{ app_loc }}"
      remote_src: yes
      owner: "{{app_user}}"
      group: "{{app_user}}"