 - name: Set Prompt with component
   ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

 - name: Install Node Exporter
   ansible.builtin.import_role:
      name: prometheus
      tasks_from: node_exporter

 - name: Install logstash
   ansible.builtin.import_role:
      name: logstash
   when: logstash_config_needed


 - name: Install configuration
   ansible.builtin.import_role:
      name: rsyslog
   when: rsyslog_config_needed
